
version: 0.0
os: linux
files:
  - source: build/index.html
    destination: /var/www/html/
  - source: build/service-worker.js
    destination: /var/www/html/  
  - source: build/asset-manifest.json
    destination: /var/www/html/  
  - source: build/favicon.ico
    destination: /var/www/html/  
hooks:
  BeforeInstall:
    - location: scripts/install
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/deploy
      timeout: 300
      runas: root  
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
