#!/bin/bash
#aws s3 cp s3://shopping-cart-jmonicam-cr3/build.tar .
#aws s3 cp s3://shopping-cart-jmonicam-cr3/index.html .
pwd
ls
sed -i -e "s/reactjs-shopping-cart//g" /var/www/html/index.html 
SERVER=$(hostname -f)
sed -i -e "s/HOSTNAME/$SERVER/g" /var/www/html/index.html
